name: Python Test and Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
         fetch-depth: 1
         submodules: true
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build twine
    - name: build package
      run: |
        python -m build --sdist .
    - name: twine test
      run: |
        python -m twine check dist/*
    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: python-packages
        path: dist
    - name: List
      run: |
        ls -la dist


  build:
    needs: package
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13]
        python-version: ['3.8', '3.11']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/download-artifact@v4.1.9
      id: download
      with:
        name: python-packages
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install tools
      run: |
        python -m pip install --upgrade pip
    - name: Build and Install SimpleITK Package
      run: |
        python -m pip install  ${{steps.download.outputs.download-path}}/simpleitk-*.tar.gz
